services:
  web-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.test
    depends_on:
      - postgres-test

  postgres-test:
    image: postgres:17
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-test.sql:/docker-entrypoint-initdb.d/init-test.sql

volumes:
  postgres_test_data: