### Test Home Route
GET http://127.0.0.1:5000/

### Test Natural Language Query
POST http://127.0.0.1:5000/queries
Content-Type: application/json

{
    "query": "find all artists who have released more than 10 albums"
}

### Test Table List
GET http://127.0.0.1:5000/tables

### Test Table Details
GET http://127.0.0.1:5000/table-details/album
