### Create a new database connection
POST http://127.0.0.1:8080/connections
Content-Type: application/json

{
    "name": "Admin Adventureworks Connection",
    "host": "localhost",
    "port": 5432,
    "username": "lawrencephan",
    "password": "",
    "database": "adventureworks"
}

### Create another database connection
POST http://127.0.0.1:8080/connections
Content-Type: application/json

{
    "name": "Chinook Connection",
    "host": "localhost",
    "port": 5432,
    "username": "lawrencephan",
    "password": "",
    "database": "chinook"
}

### Get all database connections
GET http://127.0.0.1:8080/connections

### Update a database connection
PUT http://127.0.0.1:8080/connections/1
Content-Type: application/json

{
    "name": "HR Adventureworks Connection",
    "host": "localhost",
    "port": 5432,
    "username": "hr_user",
    "password": "hr_password",
    "database": "adventureworks"
}

### Delete a database connection
DELETE http://127.0.0.1:8080/connections/4

### Get database name
GET http://127.0.0.1:8080/db-name?connection_id=1

### Get schema of the database
GET http://127.0.0.1:8080/schema?connection_id=4

### Generate descriptions for tables and columns
POST http://127.0.0.1:8080/generate-descriptions?connection_id=100

### List all available tables in the database
GET http://127.0.0.1:8080/tables?connection_id=1

### Get details of a specific table in the database
GET http://127.0.0.1:8080/table-details/employee?connection_id=1&schema_name=humanresources

### Analyze a SQL query for appropriate table name and description
POST http://127.0.0.1:8080/analyze?connection_id=1
Content-Type: application/json

{
    "query": "list all artists"
}

### Execute a natural language query
POST http://127.0.0.1:8080/queries?connection_id=2
Content-Type: application/json

{
    "query": "list all people and their email addresses"
}