name: CI Pipeline

# Trigger workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
      - test-ci
  pull_request:
    branches:
      - main
      - test-ci

jobs:
  test_backend:
    # Run backend tests on latest Linux ubuntu environment
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      # Uses checkout to pull code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Set up Python version to 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install the necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      # Run Linting using flake8 to ensure code is formatted properly
      - name: Run Linting
        run: |
          pip install flake8
          flake8 backend/

      # Run unit tests and generate coverage report
      - name: Run Unit Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest --cov=backend tests/
      
      # Upload coverage report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
