name: CI Pipeline

# Trigger workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_backend:
    # Run backend tests on latest Linux ubuntu environment
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      # Uses checkout to pull code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python version to 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install the necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-mock
      
      - name: Set OpenAI API Key
        run: echo "Setting OpenAI API Key"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      # Run Linting using flake8 to ensure code is formatted properly
      - name: Run Linting
        run: |
          pip install flake8
          flake8 backend/

      # Placeholder Test Command
      - name: Run Unit Tests
        run: |
          pytest tests/
